/** Romanian/English names map to specific foods; no fuzzy automatic matches. */
export const NUTRITION_ALIASES: Record<string, readonly string[]> = {
  '20009': ['Morcov crud', 'morcov', 'morcovi', 'carrot', 'raw carrot', "morcovi baby"],
  '20034': ['Ceapă crudă', 'ceapa', 'ceapa alba', 'onion', 'raw onion'],
  '20238': ['Ceapă roșie crudă', 'ceapa rosie', 'red onion'],
  '20385': ['Roșii crude', 'rosii', 'rosie', 'tomate', 'tomato', 'tomatoes'],
  '20172': ['Roșii cherry crude', 'rosii cherry', 'cherry tomatoes'],
  '20041': ['Ardei gras crud', 'ardei gras', 'ardei gras bianca', 'ardei california', 'bell pepper', "ardei colorat", "ardei color mix", "ardei gras mix"],
  '20087': ['Ardei gras roșu crud', 'ardei gras rosu', 'ardei capia', 'ardei kapia', 'red pepper'],
  '20085': ['Ardei gras verde crud', 'ardei gras verde', 'green pepper'],
  '20168': ['Ardei gras galben crud', 'ardei gras galben', 'yellow pepper', "ardei galben"],
  '4008': ['Cartofi cruzi, curățați', 'cartof', 'cartofi', 'cartofi cruzi', 'cartofi curatati', 'cartofi baby', 'raw potato', 'potatoes'],
  '4003': ['Cartofi fierți', 'cartof fiert', 'cartofi fierti', 'boiled potato'],
  '20055': ['Țelină rădăcină crudă', 'telina', 'telina radacina', 'celeriac'],
  '20023': ['Țelină apio crudă', 'apio', 'telina apio', 'celery stalk'],
  '20020': ['Dovlecel crud', 'dovlecel', 'dovlecei', 'zucchini', 'zuchini', 'courgette'],
  '20053': ['Vinete crude', 'vanata', 'vinete', 'aubergine', 'eggplant'],
  '20019': ['Castravete crud, cu coajă', 'castravete', 'castraveti', 'cucumber'],
  '20057': ['Broccoli crud', 'broccoli', 'brocoli', 'brocolli', 'raw broccoli'],
  '20204': ['Broccoli congelat, crud', 'broccoli congelat', 'brocolli congelat', 'frozen broccoli'],
  '20016': ['Conopidă crudă', 'conopida', 'conopida proaspata', 'cauliflower'],
  '20059': ['Spanac crud', 'spanac', 'spinach', 'raw spinach'],
  '20270': ['Spanac baby crud', 'spanac baby', 'baby spanac', 'baby spinach'],
  '20151': ['Ardei iute crud', 'ardei iute', 'fresh chilli', 'fresh chili', "ardei iute rosu"],
  '20116': ['Varză albă crudă', 'varza', 'varza alba', 'white cabbage'],
  '20014': ['Varză roșie crudă', 'varza rosie', 'red cabbage'],
  '20061': ['Fasole verde crudă', 'fasole verde', 'green beans'],
  '20072': ['Mazăre crudă', 'mazare', 'peas', 'raw peas'],
  '20084': ['Mazăre congelată, crudă', 'mazare congelata', 'frozen peas'],
  '20039': ['Praz crud', 'praz', 'leek'],
  '20031': ['Salată verde crudă', 'salata verde', 'laitue', 'lettuce'],
  '20091': ['Sfeclă roșie crudă', 'sfecla', 'sfecla rosie', 'beetroot'],
  '20056': ['Ciuperci champignon crude', 'ciuperci champignon', 'champignon', 'button mushrooms', "ciuperci champinion"],
  '20010': ['Ciuperci crude, medie', 'ciuperci', 'mushrooms'],
  '20044': ['Dovleac crud', 'dovleac', 'dovleac placinta', 'pumpkin'],
  '20181': ['Păstârnac crud', 'pastarnac', 'pastranac', 'parsnip'],
  '20028': ['Fenicul crud', 'fenicul', 'fennel'],
  '20045': ['Ridichi roșii crude', 'ridichi', 'ridiche', 'ridichii', 'radish'],
  '11000': ['Usturoi crud', 'usturoi', 'garlic', 'raw garlic'],
  '11023': ['Usturoi uscat, pudră sau granule', 'usturoi granulat', 'usturoi pudra', 'garlic powder', 'granulated garlic'],
  '11014': ['Pătrunjel proaspăt', 'patrunjel', 'patrunjel proaspat', 'parsley'],
  '11093': ['Mărar proaspăt', 'marar', 'marar proaspat', 'dill'],
  '11033': ['Busuioc proaspăt', 'busuioc', 'busuioc proaspat', 'fresh basil'],
  '11032': ['Busuioc uscat', 'busuioc uscat', 'dried basil'],
  '11070': ['Cimbru proaspăt', 'cimbru proaspat', 'fresh thyme'],
  '11038': ['Cimbru uscat', 'cimbru uscat', 'dried thyme'],
  '11053': ['Foi de dafin', 'foi dafin', 'foaie dafin', 'dafin', 'bay leaf'],
  '11094': ['Coriandru proaspăt', 'coriandru proaspat', 'fresh coriander', 'cilantro'],
  '11026': ['Coriandru semințe', 'coriandru seminte', 'coriandru boabe', 'coriandru macinat', 'coriander seeds', 'ground coriander'],
  '11068': ['Rozmarin proaspăt', 'rozmarin proaspat', 'fresh rosemary'],
  '11036': ['Rozmarin uscat', 'rozmarin uscat', 'dried rosemary'],
  '11035': ['Oregano uscat', 'oregano uscat', 'oregano', 'dried oregano'],
  '11049': ['Boia pudră', 'boia', 'boia dulce', 'paprika'],
  '11015': ['Piper negru', 'piper', 'piper negru', 'piper boabe', 'black pepper'],
  '11019': ['Piper alb măcinat', 'piper alb', 'white pepper'],
  '11074': ['Ghimbir proaspăt', 'ghimbir', 'ghimbir proaspat', 'ginger'],
  '11006': ['Ghimbir pudră', 'ghimbir pudra', 'ground ginger'],
  '11017': ['Sare alimentară albă', 'sare', 'sare de masa', 'salt'],
  '11058': ['Sare iodată', 'sare iodata', 'iodized salt'],
  '18066': ['Apă de la robinet', 'apa', 'apa potabila', 'water'],
  '31016': ['Zahăr alb', 'zahar', 'zahar alb', 'white sugar', 'sugar'],
  '31008': ['Miere', 'miere', 'honey'],
  '17440': ['Ulei de floarea-soarelui', 'ulei floarea soarelui', 'ulei de floarea soarelui', 'sunflower oil'],
  '17001': ['Ulei vegetal, medie', 'ulei', 'ulei vegetal', 'vegetable oil'],
  '17270': ['Ulei de măsline extravirgin', 'ulei masline', 'ulei de masline', 'ulei masline extravirgin', 'olive oil'],
  '17130': ['Ulei de rapiță', 'ulei rapita', 'ulei de rapita', 'rapeseed oil'],
  '16150': ['Ulei de palmier rafinat', 'ulei palmier', 'ulei de palmier', 'palm oil'],
  '16050': ['Ulei de cocos virgin', 'ulei cocos virgin', 'virgin coconut oil'],
  '16400': ['Unt nesărat, minimum 80% grăsime', 'unt', 'unt 82%', 'unt 82', 'unt nesarat', 'unsalted butter'],
  '16403': ['Unt sărat, 80% grăsime', 'unt sarat', 'salted butter'],
  '9440': ['Făină albă fină de grâu', 'faina', 'faina alba', 'faina 000', 'faina de grau', 'white flour'],
  '9415': ['Făină integrală de grâu', 'faina integrala', 'whole wheat flour'],
  '9545': ['Făină de porumb', 'faina de porumb', 'corn flour'],
  '9520': ['Făină de orez', 'faina de orez', 'rice flour'],
  '9540': ['Făină de hrișcă', 'faina de hrisca', 'buckwheat flour'],
  '9510': ['Amidon de porumb', 'amidon de porumb', 'corn starch', 'cornstarch', "amidon porumb"],
  '9610': ['Griș de grâu dur, crud', 'gris', 'gris de grau', 'semolina'],
  '9100': ['Orez alb crud', 'orez', 'orez alb', 'orez crud', 'raw rice', 'white rice', "orez arborio", "orez colosal"],
  '9104': ['Orez alb fiert, fără sare', 'orez fiert', 'orez alb fiert', 'cooked rice', 'boiled rice'],
  '9103': ['Orez integral fiert, fără sare', 'orez integral fiert', 'cooked brown rice'],
  '20359': ['Linte uscată, medie', 'linte', 'linte uscata', 'dry lentils'],
  '20360': ['Linte fiartă, medie', 'linte fiarta', 'cooked lentils'],
  '20535': ['Linte roșie uscată', 'linte rosie', 'red lentils'],
  '19016': ['Lapte integral, medie', 'lapte integral', 'lapte 3.5%', 'whole milk'],
  '19033': ['Lapte semidegresat, medie', 'lapte 1.5%', 'lapte semidegresat', 'semi skimmed milk'],
  '19039': ['Lapte UHT, medie', 'lapte', 'lapte uht', 'milk'],
  '19417': ['Smântână lichidă UHT, 30% grăsime', 'smantana 30%', 'smantana lichida 30%', 'cream 30%'],
  '19410': ['Smântână groasă, 30% grăsime', 'smantana groasa 30%', 'thick cream 30%'],
  '19403': ['Cremă lactată lichidă, medie, 24,2% grăsime', 'cream fluid average'],
  '19404': ['Cremă lactată groasă, medie, 14,7% grăsime', 'cream thick average'],
  '22000': ['Ou de găină crud, fără coajă', 'ou', 'oua', 'ou crud', 'oua crude', 'egg', 'raw egg'],
  '22001': ['Albuș crud', 'albus', 'albus de ou', 'egg white'],
  '22002': ['Gălbenuș crud', 'galbenus', 'galbenus de ou', 'egg yolk'],
  '22010': ['Ou fiert tare', 'ou fiert', 'oua fierte', 'hard boiled egg'],
  '36017': ['Piept de pui crud, fără piele', 'piept de pui', 'piept pui', 'piept pui crud', 'chicken breast'],
  '36018': ['Piept de pui gătit la grătar', 'piept de pui la gratar', 'piept pui la gratar', 'grilled chicken breast'],
  '36024': ['Pulpă de pui crudă, fără piele', 'pulpa pui dez', 'pulpa pui dezosata', 'pulpa de pui dezosata'],
  '36019': ['Pulpă superioară de pui crudă, fără piele', 'pulpa superioara de pui fara piele', 'pulpe superioare de pui fara piele'],
  '36003': ['Carne de pui crudă', 'carne pui', 'carne de pui', 'carne pui tocata', 'carne de pui tocata', 'raw chicken meat'],
  '36002': ['Pulpă de pui crudă, cu piele', 'pulpa pui intreg', 'pulpa pui cu piele', "pulpa pui superioara os"],
  '36022': ['Ciocănele de pui crude', 'ciocanele pui', 'ciocanele de pui', 'chicken drumstick'],
  '36023': ['Aripi de pui crude, cu piele', 'aripi pui', 'aripi de pui', 'chicken wings'],
  '36304': ['Piept de curcan crud', 'piept curcan', 'piept de curcan', 'turkey breast'],
  '28001': ['Spată de porc crudă', 'spata porc', 'spata de porc', 'pork shoulder'],
  '28102': ['Pulpă de porc crudă', 'pulpa porc', 'pulpa de porc'],
  '28473': ['Pulpă de porc crudă, dezosată și degresată', 'pulpa de porc dezosata degresata', 'pulpa porc dezosata degresata'],
  '28474': ['Ciolan de porc crud, dezosat și degresat', 'ciolan porc dezosat degresat', 'ciolan de porc dezosat degresat'],
  '28302': ['Ceafă de porc crudă', 'ceafa porc', 'ceafa de porc', 'pork neck'],
  '28204': ['Mușchiuleț de porc crud', 'muschiulet porc', 'muschiulet de porc', 'pork tenderloin'],
  '28100': ['Cotlet de porc crud', 'cotlet porc', 'cotlet porc f os', 'cotlet de porc', 'pork chop'],
  '6116': ['Mușchi de vită crud', 'muschi vita', 'muschi de vita', 'beef tenderloin'],
  '6201': ['Steak de vită crud', 'steak vita', 'steak de vita', 'beef steak'],
  '6250': ['Carne tocată de vită, 5% grăsime, crudă', 'vita tocata 5%', 'minced beef 5%'],
  '6252': ['Carne tocată de vită, 10% grăsime, crudă', 'vita tocata 10%', 'minced beef 10%'],
  '26036': ['Somon de crescătorie crud', 'somon', 'file somon', 'somon crud', 'salmon'],
  '13009': ['Lămâie crudă, fără coajă și sâmburi', 'lamaie', 'lemon', "lamaie proaspata"],
  '13067': ['Lime crud, fără coajă și sâmburi', 'lime', 'lamaie verde'],
  '13004': ['Avocado crud, fără coajă și sâmbure', 'avocado'],
  '13039': ['Măr crud, cu coajă', 'mar', 'mere', 'apple'],
  '13005': ['Banană crudă, fără coajă', 'banana', 'banane', 'banana raw'],
  '15000': ['Migdale crude, fără sare', 'migdale', 'almonds'],
  '15004': ['Alune de pădure, fără sare', 'alune de padure', 'hazelnuts', "alune padure"],
  '15026': ['Nuci pecan, fără sare', 'nuci pecan', 'pecan'],
  '11010': ['Drojdie proaspătă de panificație', 'drojdie proaspata', 'fresh yeast'],
  '11045': ['Drojdie uscată de panificație', 'drojdie uscata', 'dry yeast'],
  '11046': ['Praf de copt', 'praf de copt', 'baking powder'],
  '11013': ['Muștar, medie', 'mustar', 'mustard'],
  '11018': ['Oțet, medie', 'otet', 'vinegar'],
  '11090': ['Oțet de mere', 'otet de mere', 'apple cider vinegar'],
  '11091': ['Oțet balsamic', 'otet balsamic', 'balsamic vinegar'],
  '20068': ['Pastă de tomate concentrată', 'pasta tomate', 'pasta de tomate', 'tomato paste'],
  '20048': ['Roșii decojite în conservă, scurse', 'rosii decojite', 'peeled canned tomatoes drained'],
  '20137': ['Roșii decojite în suc, conservă', 'rosii in bulion', 'canned tomatoes in juice'],
  '12120': ['Parmezan', 'parmezan', 'parmesan'],
  '19590': ['Mozzarella din lapte de vacă', 'mozzarella', 'mozarella', 'mozzarella de vaca'],
  '19591': ['Mozzarella din lapte de bivoliță', 'mozzarella di bufala', 'mozzarella de bivolita'],
  '19593': ['Iaurt natural', 'iaurt', 'iaurt natural', 'plain yoghurt', 'plain yogurt'],
  '19860': ['Iaurt grecesc natural', 'iaurt grecesc', 'greek yoghurt'],
  '19594': ['Iaurt natural 0% grăsime', 'iaurt 0%', 'iaurt degresat', 'fat free yoghurt'],
  '9810': ['Paste uscate din grâu, crude', 'paste', 'paste uscate', 'penne', 'spaghetti', 'spaghete', 'fusilli', 'dry pasta', "foi lasagna", "penne tricolore", "paste penne crude", "paste lasagna uscate"],
  '9811': ['Paste fierte, fără sare', 'paste fierte', 'cooked pasta'],
  '9821': ['Paste uscate cu ou, crude', 'paste cu ou', 'taitei cu ou', 'dry egg pasta', "fidea cu ou", "tagliatelle cu ou uscate", "taitei cu ou uscati"],
  '9900': ['Tăiței uscați de orez', 'taitei orez', 'taitei de orez', 'dry rice noodles'],
  '9901': ['Tăiței de orez fierți', 'taitei de orez fierti', 'cooked rice noodles'],
  '9870': ['Paste integrale uscate, crude', 'paste integrale', 'whole wheat pasta', "penne integrale", "paste integrale crude", "whole wheat pasta raw"],
  '9102': ['Orez integral crud', 'orez integral', 'raw brown rice'],
  '9614': ['Mălai/semolă de porumb pentru polenta', 'malai', 'polenta dry'],
  '7500': ['Pesmet', 'pesmet', 'breadcrumbs'],
  '11104': ['Sos de soia', 'sos soia', 'sos de soia', 'soy sauce'],
  '11216': ['Sos de soia dulce', 'sos soia dulce', 'sweet soy sauce'],
  '31017': ['Zahăr brun', 'zahar brun', 'brown sugar'],
  '31074': ['Ciocolată neagră, aproximativ 70% cacao', 'ciocolata neagra 70%', 'dark chocolate 70%'],
  '31085': ['Ciocolată neagră pentru gătit', 'ciocolata pentru gatit', 'cooking chocolate'],
  '2028': ['Suc pur de lămâie', 'suc lamaie', 'suc de lamaie', 'lemon juice'],
  '2031': ['Suc pur de lime', 'suc lime', 'lime juice'],
  '15005': ['Miez de nucă uscat', 'nuci', 'miez de nuca', 'miez nuca', 'walnuts'],
  '15010': ['Semințe de susan', 'susan', 'seminte susan', 'sesame seeds', "susan alb", "susan negru"],
  '15011': ['Semințe de floarea-soarelui', 'seminte floarea soarelui', 'sunflower seeds'],
  '15035': ['Susan alb decorticat', 'susan alb decorticat', 'susan decorticat', 'hulled sesame seeds', "hulled sesame"],
  '13184': ['Măsline, medie', 'masline', 'olives'],
  '13032': ['Măsline negre în saramură, scurse', 'masline negre in saramura', 'black olives in brine drained'],
  '13033': ['Măsline verzi în saramură, scurse', 'masline verzi in saramura', 'green olives in brine drained'],
  '20189': ['Roșii uscate', 'rosii uscate', 'dried tomatoes'],
  '20256': ['Roșii uscate în ulei', 'rosii uscate in ulei', 'sun dried tomatoes in oil'],
  '20066': ['Porumb dulce în conservă, scurs', 'porumb dulce conserva', 'porumb la conserva', 'canned sweetcorn drained'],
  '7815': ['Foi tortilla din grâu', 'foi tortilla grau', 'tortilla de grau', 'wheat tortilla'],
  '7813': ['Foi tortilla din porumb', 'foi tortilla porumb', 'tortilla de porumb', 'corn tortilla'],
  '28910': ['Șuncă fiartă, calitate standard', 'sunca fiarta', 'cooked ham'],
  '28502': ['Piept de porc sărat și afumat, crud', 'piept porc sarat afumat', 'bacon din piept de porc crud'],
  '28727': ['Bacon din file de porc', 'bacon file', 'bacon din file de porc'],
  '5214': ['Vin roșu', 'vin rosu', 'red wine'],
  '5215': ['Vin alb sec', 'vin alb sec', 'dry white wine'],
  '11107': ['Sos de roșii cu ceapă, ambalat', 'sos de rosii cu ceapa ambalat', 'packaged tomato onion sauce'],
  '11004': ['Castraveți murați în oțet', 'castraveti murati in otet', 'pickled gherkins'],
  '12726': ['Cheddar', 'cheddar', 'branza cheddar', 'branza cedar', 'cedar'],
  '12115': ['Emmental', 'emmental', 'emmentaler', 'ementaler'],
  '12114': ['Gruyère', 'gruyere'],
  '19585': ['Ricotta', 'ricotta'],
  '12066': ['Feta din lapte de oaie și capră', 'feta', 'branza feta'],
  '9681': ['Couscous uscat, din grâu dur', 'couscous', 'cous cous', 'cuscus', 'dry couscous'],
  '4101': ['Cartof dulce crud', 'cartof dulce', 'cartofi dulci', 'raw sweet potato'],
  '10021': ['Creveți cruzi', 'creveti cruzi', 'raw shrimp'],
  '40111': ['Ficat de pui crud', 'ficat pui', 'ficat de pui', 'ficatei pui', 'raw chicken liver'],
  '20501': ['Fasole albă uscată', 'fasole alba uscata', 'fasole uscata', 'dry white beans'],
  '20525': ['Fasole roșie uscată', 'fasole rosie uscata', 'dry kidney beans'],
  '20516': ['Năut uscat', 'naut', 'naut uscat', 'dry chickpeas'],
  '13002': ['Ananas crud, fără coajă', 'ananas', 'pineapple'],
  '13014': ['Căpșuni crude', 'capsuni', 'strawberries'],
  '13015': ['Zmeură crudă', 'zmeura', 'raspberries'],
  '13021': ['Kiwi crud, fără coajă', 'kiwi'],
  '13025': ['Mango crud, fără coajă și sâmbure', 'mango'],
  '13037': ['Pară crudă, cu coajă', 'para', 'pere', 'pear'],
  '13034': ['Portocală crudă, fără coajă și sâmburi', 'portocala', 'portocale', 'orange'],
  '11025': ['Scorțișoară pudră', 'scortisoara', 'scortisoara macinata', 'cinnamon'],
  '11042': ['Chimion semințe sau pudră', 'chimion', 'chimion pudra', 'cumin'],
  '11064': ['Chimen semințe', 'chimen', 'chimen seminte', 'seminte chimen', 'caraway seeds'],
  '11089': ['Curcuma/turmeric pudră', 'curcuma', 'curcuma pudra', 'turmeric', 'turmeric pudra', 'ground turmeric'],
  '11048': ['Nucșoară', 'nucsoara', 'nutmeg'],
  '11005': ['Curry pudră', 'curry pudra', 'pudra curry', 'curry powder'],
  '11052': ['Cuișoare uscate', 'cuisoare', 'cuisoare macinate', 'cloves'],
  '11066': ['Fenicul semințe', 'seminte fenicul', 'fennel seeds'],
  '11069': ['Salvie proaspătă', 'salvie proaspata', 'fresh sage'],
  '11092': ['Tarhon proaspăt', 'tarhon proaspat', 'fresh tarragon'],
  '17400': ['Ulei de susan', 'ulei susan', 'ulei de susan', 'sesame oil'],
  '13046': ['Stafide', 'stafide', 'raisins'],
  '13018': ['Rodie, boabe crude', 'rodie', 'pomegranate'],
  '20167': ['Varză chinezească crudă', 'varza china', 'varza chinezeasca', 'raw Chinese cabbage'],
  '20217': ['Rucola crudă', 'rucola', 'rucolla', 'rocket', 'arugula'],
  '18041': ['Lapte de cocos', 'lapte cocos', 'lapte de cocos', 'coconut milk'],
  '20532': ['Năut în conservă, scurs', 'naut conserva', 'naut la conserva', 'canned chickpeas drained'],
  '20524': ['Fasole roșie în conservă, scursă', 'fasole rosie conserva', 'fasole rosie la conserva', 'canned kidney beans drained'],
  '11008': ['Ketchup ambalat', 'ketchup', 'ketchup dulce'],
  '11054': ['Maioneză ambalată, minimum 70% grăsime', 'maioneza', 'mayonnaise'],
  '11223': ['Sos de stridii', 'sos stridii', 'sos de stridii', 'oyster sauce'],
  '11194': ['Sos de pește', 'sos peste', 'sos de peste', 'fish sauce'],
  '11301': ['Sos teriyaki', 'sos teriyaki', 'sos teriaky', 'teriyaki sauce'],
  '26043': ['Cod crud', 'file cod', 'cod crud', 'raw cod'],
  '26044': ['Merluciu crud', 'merluciu', 'merluciu trunchi', 'raw hake'],
  '26082': ['Pește spadă crud', 'file spada', 'peste spada', 'raw swordfish'],
  '26079': ['Hamsii crude', 'hamsie', 'hamsii', 'hamsie congelata', 'raw anchovy'],
  '26065': ['Sardine crude', 'sardine', 'sardine crude', 'raw sardines'],
  '12020': ['Brie', 'brie', 'branza brie'],
  '11040': ['Capere în oțet', 'capere', 'capers in vinegar'],
  '15064': ['Semințe de dovleac uscate', 'seminte dovleac', 'seminte de dovleac', 'pumpkin seeds'],
  '15034': ['Semințe de in', 'seminte in', 'seminte de in', 'flax seeds'],
  '9340': ['Quinoa crudă', 'quinoa', 'quinoa cruda', 'raw quinoa'],
  '9119': ['Orez basmati sau jasmin, crud', 'orez basmati', 'orez basmatic', 'orez jasmin', 'raw basmati rice'],
  '9108': ['Orez sălbatic crud', 'orez salbatic', 'raw wild rice'],
  '11027': ['Mentă proaspătă', 'menta', 'menta proaspata', 'fresh mint'],
  '11029': ['Mentă uscată', 'menta uscata', 'dried mint'],
  "11003": ["Ceapă verde sau arpagic proaspăt", "ceapa verde", "ceapa verde cruda", "spring onion", "scallion"],
  "28400": ["Coaste de porc crude", "scaricica", "scaricica porc", "coaste porc crude", "pork spare ribs raw"],
  "28002": ["Piept de porc crud", "fleica porc", "piept porc", "piept porc fara os", "pork belly raw"],
  "36307": ["Pulpă de curcan crudă, fără piele", "pulpa curcan fara piele", "pulpe superioare dezosate curcan fara piele", "raw turkey thigh without skin"],
  "30315": ["Chorizo, medie", "salam chorizo", "chorizo"],
  "7001": ["Pâine albă", "paine franzela", "paine alba", "white bread"],
  "7180": ["Lipie pita", "lipie pita", "pita bread"],
  "7259": ["Chiflă pentru hamburger", "chifla hamburger", "chifla burger", "hamburger bun"],
  "13042": ["Prune uscate, fără sâmburi", "prune uscate", "prune deshidratate", "dried prunes"],
  "20200": ["Salată iceberg crudă", "salata iceberg", "iceberg lettuce"],
  "11021": ["Muștar cu boabe", "mustar boabe", "mustar cu boabe", "wholegrain mustard"],
  "40205": ["Limbă de porc crudă", "limba porc", "limba de porc", "raw pork tongue"],
  "4090": ["Amidon de cartofi", "amidon cartofi", "amidon de cartofi", "potato starch"],
  "12040": ["mozarella mini"],
  "20114": ["ciuperci pleurotus"],
  "20211": ["Ciuperci shiitake uscate", "shiitake uscate", "dried shiitake"],
};

/** Generic kitchen names use explicit, unconfirmed assumptions, never a product label. */
export const NUTRITION_ESTIMATED_ALIASES: Record<string, { names: readonly string[]; assumption: string }> = {
  '19403': { names: ['smantana lichida', 'smantana pentru gatit', 'crema lactata lichida'], assumption: 'Cremă lactată lichidă, medie Ciqual: 24,2% grăsime. Verifică eticheta produsului.' },
  '19404': { names: ['smantana'], assumption: 'Cremă lactată groasă, medie Ciqual: 14,7% grăsime. Verifică eticheta produsului.' },
  '22000': { names: ['ou melange', 'ou melanj', 'melange ou', 'melanj ou', 'ou lichid integral'], assumption: 'Ou întreg, fără coajă și fără adaosuri. Verifică melanjul folosit.' },
  '25525': { names: ['sos rosii', 'sos de rosii'], assumption: 'Sos de roșii gătit pentru pizza, Ciqual. Pentru sos propriu folosește semipreparatul; pentru produs ambalat verifică eticheta.' },
  '5215': { names: ['vin alb'], assumption: 'Vin alb sec, Ciqual. Pentru vin dulce sau demisec verifică produsul; pierderea alcoolului la gătire nu este calculată.' },
};

/** Extra search choices let the operator replace a generic estimate with the exact food. */
export const NUTRITION_SEARCH_TERMS: Record<string, readonly string[]> = {
  '19417': ['smantana lichida', 'smantana', 'cream'],
  '19410': ['smantana', 'sour cream'],
  '19403': ['smantana lichida', 'smantana', 'cream'],
  '19404': ['smantana', 'sour cream'],
  '22000': ['ou melange', 'melange ou', 'ou lichid'],
  '22001': ['ou melange', 'melange ou', 'ou lichid'],
  '22002': ['ou melange', 'melange ou', 'ou lichid'],
  '9510': ['amidon'],
  '96781': ['amidon'],
  '11094': ['coriandru'],
  '11026': ['coriandru'],
  '11068': ['rozmarin'],
  '11036': ['rozmarin'],
  '11070': ['cimbru'],
  '11038': ['cimbru'],
  '28910': ['sunca presata'],
  '28913': ['sunca presata'],
  '11107': ['sos rosii', 'sos de rosii'],
  '25525': ['sos rosii', 'sos de rosii'],
  '7815': ['foi tortilla', 'tortilla'],
  '7813': ['foi tortilla', 'tortilla'],
  '5215': ['vin alb'],
  '20066': ['porumb'],
  '20233': ['porumb'],
  '20108': ['porumb'],
  '28502': ['bacon'],
  '28727': ['bacon'],
};
